# Generated by Django 4.2.23 on 2025-08-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('email_contato', models.EmailField(max_length=254, unique=True)),
                ('preco_por_ipu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'api_clientes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoIDMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido_configuracao', models.CharField(max_length=255)),
                ('iics_pod_url', models.TextField()),
                ('iics_username', models.TextField()),
                ('iics_password', models.TextField()),
                ('ultima_extracao_enddate', models.DateTimeField(blank=True, help_text='Marcador da última data final usada na extração', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='api.clientes')),
            ],
            options={
                'verbose_name_plural': 'Configurações IDMC',
                'db_table': 'api_configuracaoidmc',
                'ordering': ['cliente', 'apelido_configuracao'],
            },
        ),
        migrations.CreateModel(
            name='ExtracaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.CharField(help_text='Ex: LOGIN, EXPORT_JOB, DOWNLOAD, LOAD_CSV', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes como job_type, meter_id, etc.', null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('resposta_api', models.TextField(blank=True, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Logs de Extração',
                'db_table': 'api_extracaolog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consumption_date', models.DateField(blank=True, null=True)),
                ('billing_period_start_date', models.DateField(blank=True, null=True)),
                ('billing_period_end_date', models.DateField(blank=True, null=True)),
                ('meter_usage', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('consumption_ipu', models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True)),
                ('scalar', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_category', models.CharField(blank=True, max_length=255, null=True)),
                ('org_name', models.CharField(blank=True, max_length=255, null=True)),
                ('org_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ipu_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Consumos (Summary)',
                'db_table': 'api_consumosummary',
            },
        ),
        migrations.CreateModel(
            name='ConsumoProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('consumption_date', models.DateField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('folder_path', models.TextField(blank=True, null=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_consumption_ipu', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Consumos (Project/Folder)',
                'db_table': 'api_consumoprojectfolder',
            },
        ),
        migrations.CreateModel(
            name='ConsumoCdiJobExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('meter_id_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('task_object_name', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, max_length=255, null=True)),
                ('task_run_id', models.TextField(unique=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('environment_id', models.TextField(blank=True, null=True)),
                ('environment_name', models.TextField(blank=True, null=True)),
                ('cores_used', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('metered_value_ipu', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('audit_time', models.DateTimeField(blank=True, null=True)),
                ('obm_task_time_seconds', models.IntegerField(blank=True, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Consumos (CDI Job)',
                'db_table': 'api_consumocdijobexecucao',
            },
        ),
        migrations.CreateModel(
            name='ConsumoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('meter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consumption_date', models.DateField(blank=True, null=True)),
                ('asset_name', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('org_type', models.CharField(blank=True, max_length=100, null=True)),
                ('runtime_environment', models.CharField(blank=True, max_length=255, null=True)),
                ('environment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tier', models.CharField(blank=True, max_length=100, null=True)),
                ('ipu_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('usage', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('consumption_ipu', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Consumos (Asset)',
                'db_table': 'api_consumoasset',
            },
        ),
        migrations.CreateModel(
            name='ConsumoCaiAssetSumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_extracao', models.DateField(auto_now_add=True)),
                ('org_id', models.TextField(blank=True, null=True)),
                ('execution_type', models.CharField(blank=True, max_length=255, null=True)),
                ('executed_asset', models.TextField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('invoked_by', models.TextField(blank=True, null=True)),
                ('execution_env', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_count', models.BigIntegerField(blank=True, null=True)),
                ('total_execution_time_hours', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('avg_execution_time_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name_plural': 'Consumos (CAI Summary)',
                'db_table': 'api_consumocaiassetsumario',
                'unique_together': {('configuracao', 'executed_asset', 'execution_date', 'execution_type')},
            },
        ),
    ]
