# Generated by Django 4.2.23 on 2025-08-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoasset',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumocaiassetsumario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumocdijobexecucao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumoprojectfolder',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumosummary',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consumoasset',
            name='consumption_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumoasset',
            name='data_extracao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumocaiassetsumario',
            name='data_extracao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumocaiassetsumario',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumocdijobexecucao',
            name='data_extracao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumoprojectfolder',
            name='consumption_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumoprojectfolder',
            name='data_extracao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consumosummary',
            name='billing_period_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumosummary',
            name='billing_period_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumosummary',
            name='consumption_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumosummary',
            name='data_extracao',
            field=models.DateTimeField(),
        ),
    ]
