# Generated by Django 4.2.23 on 2025-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consumoasset_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumocdijobexecucao',
            name='task_run_id',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='consumoasset',
            unique_together={('configuracao', 'meter_id', 'consumption_date', 'asset_name', 'asset_type', 'project_name', 'folder_name', 'org_id', 'runtime_environment')},
        ),
        migrations.AlterUniqueTogether(
            name='consumocaiassetsumario',
            unique_together={('configuracao', 'org_id', 'executed_asset', 'execution_date', 'execution_env')},
        ),
        migrations.AlterUniqueTogether(
            name='consumocdijobexecucao',
            unique_together={('configuracao', 'task_id', 'task_run_id', 'org_id', 'environment_id')},
        ),
        migrations.AlterUniqueTogether(
            name='consumoprojectfolder',
            unique_together={('configuracao', 'consumption_date', 'project_name', 'folder_path', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='consumosummary',
            unique_together={('configuracao', 'org_id', 'meter_id', 'consumption_date')},
        ),
    ]
