# Generated by Django 4.2.23 on 2025-08-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_consumocdijobexecucao_task_run_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumoasset',
            unique_together={('configuracao', 'meter_id', 'consumption_date', 'asset_name', 'asset_type', 'project_name', 'folder_name', 'org_id', 'runtime_environment', 'tier', 'ipu_per_unit')},
        ),
    ]
