# Generated by Django 4.2.23 on 2025-08-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_consumoasset_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumocdijobexecucao',
            unique_together={('configuracao', 'task_id', 'task_run_id', 'org_id', 'environment_id', 'start_time', 'end_time')},
        ),
    ]
