# Generated by Django 4.2.23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fix_cdi_unique_constraint_manual'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumocaiassetsumario',
            unique_together={('configuracao', 'org_id', 'executed_asset', 'execution_date', 'execution_env', 'status')},
        ),
    ]