# Generated by Django 4.2.23 on 2025-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250814_2004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumocaiassetsumario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='consumocaiassetsumario',
            name='invoked_by',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='consumocaiassetsumario',
            unique_together={('configuracao', 'org_id', 'executed_asset', 'execution_date', 'execution_env', 'status', 'invoked_by')},
        ),
    ]
