# Generated by Django 4.2.23 on 2025-08-15 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_consumocaiassetsumario_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcadorExtracao',
            fields=[
                ('configuracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.configuracaoidmc', verbose_name='Configuração')),
                ('ultima_extracao_enddate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Final da Última Extração')),
            ],
            options={
                'verbose_name': 'Marcador de Extração',
                'verbose_name_plural': 'Marcadores de Extração',
                'db_table': 'api_marcadorextracao',
            },
        ),
    ]
