# Generated by Django 4.2.23 on 2025-08-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_marcadorextracao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarcadorExtracao',
        ),
    ]
