# Generated by Django 4.2.23 on 2025-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_marcadorextracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='qnt_ipus_contratadas',
            field=models.DecimalField(decimal_places=4, default=120, max_digits=10),
            preserve_default=False,
        ),
    ]
