# Generated by Django 4.2.23 on 2025-08-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_marcadorextracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_id', models.IntegerField()),
                ('billing_period_start_date', models.DateField()),
                ('billing_period_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_faturamento', to='api.configuracaoidmc')),
            ],
            options={
                'verbose_name': 'Ciclo de Faturamento',
                'verbose_name_plural': 'Ciclos de Faturamento',
                'ordering': ['configuracao', 'billing_period_start_date'],
                'unique_together': {('configuracao', 'ciclo_id'), ('configuracao', 'billing_period_start_date', 'billing_period_end_date')},
            },
        ),
        migrations.DeleteModel(
            name='MarcadorExtracao',
        ),
    ]
