# Generated by Django 4.2.23 on 2025-08-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ciclofaturamento_delete_marcadorextracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocaiassetsumario',
            name='meter_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consumocdijobexecucao',
            name='meter_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
