// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiuyzzrhlwzflxczdctb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdXl6enJobHd6Zmx4Y3pkY3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjM3OTAsImV4cCI6MjA3MDgzOTc5MH0.OEvgT05a26JT-_YIrgRI7TPJOB7K1FrssJGTT-5amIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});